services:
  frontend:
    container_name: frontend 
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - "3000:3000"
    networks:
      - rope-network
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    container_name: backend 
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - "8080:8080"
    networks:
      - rope-network
  
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: alfie
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rope-network

networks:
  rope-network:
    driver: bridge

volumes:
  db_data:
